"""MCP server for Animato.

Exposes the local animation engine to MCP hosts such as GPT, Claude, Grok,
Cursor, VS Code and other compatible clients.

By default, arbitrary bpy execution is disabled. Set
ANIMATO_MCP_ALLOW_CODE_EXECUTION=true only for a trusted local MCP setup.
"""

from __future__ import annotations

import json
import os
import subprocess
import sys
from pathlib import Path
from typing import Annotated

from mcp.server import MCPServer
from mcp.types import ToolAnnotations
from pydantic import Field

from app.animation_worker import _make_matcher
from app.config import ALLOWED_EXTENSIONS, PUBLIC_DIR, UPLOAD_DIR
from app.routers.prompt import build_prompt_for_upload
from app.routers.run import execute_bpy_code

mcp = MCPServer(
    "Animato",
    version="0.2.0",
    instructions=(
        "Animato is a local-first text-to-animation engine for rigged 3D "
        "models. Inspect models, prepare animation prompts, then generate "
        "Blender Python in the calling AI and execute it only when local "
        "code execution has explicitly been enabled."
    ),
)


def _safe_model_path(filename: str) -> Path:
    name = Path(filename).name
    if not name or name != filename:
        raise ValueError("filename must be a simple uploaded filename")
    path = (Path(UPLOAD_DIR) / name).resolve()
    upload_root = Path(UPLOAD_DIR).resolve()
    if path.parent != upload_root:
        raise ValueError("filename must stay inside the upload directory")
    if path.suffix.lower() not in ALLOWED_EXTENSIONS:
        raise ValueError(
            f"unsupported model format; allowed: {', '.join(sorted(ALLOWED_EXTENSIONS))}"
        )
    if not path.is_file():
        raise FileNotFoundError(f"model not found: {name}")
    return path


@mcp.tool(
    title="List uploaded 3D models",
    annotations=ToolAnnotations(read_only_hint=True, open_world_hint=False),
)
def list_models() -> list[dict[str, object]]:
    """List uploaded OBJ, GLB and FBX models available to the local engine."""
    result: list[dict[str, object]] = []
    root = Path(UPLOAD_DIR)
    for path in sorted(root.iterdir(), key=lambda p: p.name.lower()):
        if path.is_file() and path.suffix.lower() in ALLOWED_EXTENSIONS:
            result.append(
                {
                    "filename": path.name,
                    "extension": path.suffix.lower(),
                    "size_bytes": path.stat().st_size,
                }
            )
    return result


@mcp.tool(
    title="Prepare an animation prompt",
    annotations=ToolAnnotations(read_only_hint=True, open_world_hint=False),
)
def prepare_animation(
    filename: Annotated[str, Field(description="Uploaded model filename.")],
    animation: Annotated[
        str,
        Field(
            min_length=1,
            max_length=2000,
            description="Natural-language description of the desired animation.",
        ),
    ],
) -> dict[str, str]:
    """Build the same model-aware prompt used by Animato's web UI."""
    path = _safe_model_path(filename)
    prompt, output_url = build_prompt_for_upload(path.name, animation)
    return {
        "filename": path.name,
        "prompt": prompt,
        "output_url": output_url,
        "next_step": (
            "Generate Blender Python from this prompt in the calling AI, then "
            "call run_animation_code when local code execution is explicitly enabled."
        ),
    }


@mcp.tool(
    title="Run generated Blender animation code",
    annotations=ToolAnnotations(
        destructive_hint=True,
        idempotent_hint=False,
        open_world_hint=False,
    ),
)
def run_animation_code(
    code: Annotated[
        str,
        Field(
            min_length=1,
            max_length=120000,
            description="Blender Python generated by the calling AI for the selected model.",
        ),
    ],
) -> dict[str, object]:
    """Execute generated bpy code in Animato's isolated runner.

    This tool is disabled by default because the underlying engine intentionally
    executes Python. Enable it only in a trusted local MCP deployment with
    ANIMATO_MCP_ALLOW_CODE_EXECUTION=true.
    """
    if os.getenv("ANIMATO_MCP_ALLOW_CODE_EXECUTION", "").lower() != "true":
        return {
            "ok": False,
            "error": (
                "Code execution is disabled. Set "
                "ANIMATO_MCP_ALLOW_CODE_EXECUTION=true only for a trusted "
                "local MCP server."
            ),
        }
    return execute_bpy_code(code)


@mcp.tool(
    title="Remove an animation clip",
    annotations=ToolAnnotations(
        destructive_hint=True,
        idempotent_hint=True,
        open_world_hint=False,
    ),
)
def remove_animation(
    filename: Annotated[str, Field(description="Uploaded GLB, GLTF or FBX filename.")],
    animation_name: Annotated[
        str,
        Field(min_length=1, max_length=300, description="Animation clip/action name to remove."),
    ],
) -> dict[str, object]:
    """Remove a named animation clip using Animato's fixed Blender worker."""
    path = _safe_model_path(filename)
    if path.suffix.lower() not in {".glb", ".gltf", ".fbx"}:
        raise ValueError("animation removal is supported for GLB, GLTF and FBX")
    proc = subprocess.run(
        [sys.executable, "-m", "app.animation_worker", str(path), animation_name],
        cwd=str(Path(PUBLIC_DIR).parent),
        capture_output=True,
        text=True,
        timeout=300,
    )
    return {
        "ok": proc.returncode == 0,
        "returncode": proc.returncode,
        "filename": path.name,
        "stdout": proc.stdout,
        "stderr": proc.stderr,
    }


@mcp.tool(
    title="Get Animato MCP status",
    annotations=ToolAnnotations(read_only_hint=True, open_world_hint=False),
)
def get_mcp_status() -> dict[str, object]:
    """Return MCP and local-engine capability information."""
    return {
        "server": "Animato",
        "version": "0.2.0",
        "mcp_transports": ["stdio", "streamable-http"],
        "http_endpoint": "/mcp",
        "code_execution_enabled": os.getenv(
            "ANIMATO_MCP_ALLOW_CODE_EXECUTION", ""
        ).lower()
        == "true",
        "engine": "local Blender/bpy",
        "supported_models": sorted(ALLOWED_EXTENSIONS),
    }


# FastAPI can mount this ASGI app at /mcp.
mcp_app = mcp.streamable_http_app(streamable_http_path="/")

if __name__ == "__main__":
    # Local MCP hosts normally launch this module over stdio.
    mcp.run()
